// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace Frump
{
public static class GPGSIds
{
        public const string achievement_200m_medal = "CgkI9_qoq7gPEAIQBA"; // <GPGSID>
        public const string achievement_150m_medal = "CgkI9_qoq7gPEAIQAw"; // <GPGSID>
        public const string achievement_300m_medal = "CgkI9_qoq7gPEAIQBg"; // <GPGSID>
        public const string achievement_250m_medal = "CgkI9_qoq7gPEAIQBQ"; // <GPGSID>
        public const string achievement_400m_medal = "CgkI9_qoq7gPEAIQCA"; // <GPGSID>
        public const string achievement_350m_medal = "CgkI9_qoq7gPEAIQBw"; // <GPGSID>
        public const string leaderboard_ranking = "CgkI9_qoq7gPEAIQCQ"; // <GPGSID>
        public const string achievement_50m_medal = "CgkI9_qoq7gPEAIQAQ"; // <GPGSID>
        public const string achievement_100m_medal = "CgkI9_qoq7gPEAIQAg"; // <GPGSID>
        public const string achievement_10m_medal = "CgkI9_qoq7gPEAIQAA"; // <GPGSID>

}
}
